SELECT
    w.ID AS ID,
    wp.AGE AS AGE,
    w.COINS_NEEDED AS COINS_NEEDED,
    w.POWER AS WAND_POWER
FROM
    Wands w 
    JOIN WANDS_PROPERTY wp ON w.CODE = wp.CODE
WHERE (wp.AGE, w.COINS_NEEDED, w.POWER) IN
    (
    SELECT
        wp2.AGE AS AGE,
        MIN(w1.COINS_NEEDED) AS COINS_NEEDED,
        w1.POWER AS WAND_POWER
    FROM
        WANDS w1 JOIN WANDS_PROPERTY wp2 ON w1.CODE = wp2.CODE
    WHERE wp2.IS_EVIL = 0
    GROUP BY w1.CODE, w1.POWER, wp2.AGE
    )
ORDER BY w.POWER DESC, wp.AGE DESC;
